# Generated by Django 5.2 on 2025-04-11 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cap_coal', models.FloatField(default=0)),
                ('cap_solar', models.FloatField(default=0)),
                ('cap_nuclear', models.FloatField(default=0)),
                ('cap_wind', models.FloatField(default=0)),
                ('cap_brown_coal', models.FloatField(default=0)),
                ('cap_n_gas', models.FloatField(default=0)),
                ('cap_hydro', models.FloatField(default=0)),
                ('cap_biofuel', models.FloatField(default=0)),
                ('price_coal', models.FloatField(default=0)),
                ('price_solar', models.FloatField(default=0)),
                ('price_nuclear', models.FloatField(default=0)),
                ('price_wind', models.FloatField(default=0)),
                ('price_brown_coal', models.FloatField(default=0)),
                ('price_n_gas', models.FloatField(default=0)),
                ('price_hydro', models.FloatField(default=0)),
                ('price_biofuel', models.FloatField(default=0)),
                ('em_coal', models.FloatField(default=0)),
                ('em_solar', models.FloatField(default=0)),
                ('em_nuclear', models.FloatField(default=0)),
                ('em_wind', models.FloatField(default=0)),
                ('em_brown_coal', models.FloatField(default=0)),
                ('em_n_gas', models.FloatField(default=0)),
                ('em_hydro', models.FloatField(default=0)),
                ('em_biofuel', models.FloatField(default=0)),
                ('eff_solar', models.FloatField(default=100)),
                ('eff_wind', models.FloatField(default=100)),
                ('eff_hydro', models.FloatField(default=100)),
                ('eff_coal', models.FloatField(default=46)),
                ('eff_gas', models.FloatField(default=58)),
                ('eff_bcoal', models.FloatField(default=44)),
                ('eff_nuclear', models.FloatField(default=36)),
                ('eff_biofuel', models.FloatField(default=85)),
                ('wo_coal', models.FloatField(default=21.27)),
                ('wo_brown_coal', models.FloatField(default=85)),
                ('wo_n_gas', models.FloatField(default=48)),
                ('wo_ch4_n_gas', models.FloatField(default=36.65)),
                ('we_coal', models.FloatField(default=93.54)),
                ('we_b_coal', models.FloatField(default=111.53)),
                ('we_n_gas', models.FloatField(default=55.48)),
                ('co2_price', models.FloatField(default=80.24)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('author', 'title'), name='unique_project_per_user')],
            },
        ),
    ]
